name: Build and Deploy to GitHub Pages
on:
  push:    
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
      VITE_API_WS: ${{ secrets.VITE_API_WS }}
    steps:
      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d dist -u "github-actions-bot <support+actions@github.com>"
