name: Build and Deploy to GitHub Pages
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
      VITE_API_WS: ${{ secrets.VITE_API_WS }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - name: Deploy to GitHub Pages
        run: npm run deploy
