name: Build and Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
      VITE_API_WS: ${{ secrets.VITE_API_WS }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Build static files
        id: build
        run: |
          npm ci
          npm run build:client
  # Deployment job
  deploy:
    needs: build
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./puzzpals-client-ts/dist
